  /*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  */

  import React, { useRef } from "react";
  import { useGLTF } from "@react-three/drei";

  export default function Model(props) {
    const { nodes, materials } = useGLTF("myObj.gltf");
    return (
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.Torus002.geometry}
          material={nodes.Torus002.material}
          position={[0, 0, 0]}
        />
      </group>
    );
  }

  useGLTF.preload("./untitled.gltf");
